image: maven:3.6.0-jdk-11-slim

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --show-version -P ci"

cache:
  paths:
    - .m2/repository
    - Simulator/target/

stages:
  - build
  - test
  - prepare
  - deploy

‚öômaven-build:
  stage: build
  script:
    - cd Simulator
    - mvn $MAVEN_CLI_OPTS compile

üß™junit-test:
  stage: test
  script:
    - cd Simulator
    - mvn $MAVEN_CLI_OPTS -B test
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, "instructions covered"; print 100*covered/instructions, "% covered" }' target/site/jacoco/jacoco.csv
  coverage: '/\d+.\d+ \% covered/'
  artifacts:
    paths:
      - Simulator/target/site/jacoco/
    expire_in: 30 days

üëîcode_quality:
  image: docker:stable
  stage: prepare
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - cd Simulator
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run --env SOURCE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: Simulator/gl-code-quality-report.json

üìñjavadoc:
  stage: prepare
  script:
    - cd Simulator
# See https://bugs.openjdk.java.net/browse/JDK-8208269
    - mv src/main/java/module-info.java mudule-info.temp
    - mvn $MAVEN_CLI_OPTS -DskipTests=true -B javadoc:javadoc
    - mv mudule-info.temp src/main/java/module-info.java
  artifacts:
    paths:
      - Simulator/target/site/apidocs
    expire_in: 30 days

‚èØbuild-jar:
  stage: prepare
  script:
    - cd Simulator
    - mvn $MAVEN_CLI_OPTS -DskipTests=true -B package
    - cp target/Simulator.jar Simulator.jar
  artifacts:
    paths:
      - Simulator/instance.json
      - Simulator/Simulator.jar
      - Simulator/native
    expire_in: 30 days

üåçpages:
  stage: deploy
  script:
    - mkdir .public
    - mkdir .public/jacoco
    - mkdir .public/javadoc
    - mkdir .public/pmd
    - cp -r Simulator/target/site/jacoco/* .public/jacoco
    - cp -r Simulator/target/site/apidocs/* .public/javadoc
#    - cp Simulator/target/site/pmd.html .public/pmd/index.html
    - cp Simulator/gitlab-pages.html .public/index.html
    - mv .public public
  artifacts:
    paths:
      - public
  #    expire_in: 30 days
  only:
    - master
